---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python

- name: Install python3, docker and docker-compose on EC2
#  hosts: docker_server
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker is installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: 
         - docker
         - docker-compose

#- name: Install Docker on EC2
#  hosts: docker_server
#  become: yes
#  tasks:
#    - name: Install Docker
#      vars:
#        ansible_python_interpreter: /usr/bin/python
#      yum:
#        name: docker
#        update_cache: yes
#        state: present

#- name: Install Docker-compose
#  hosts: docker_server
#  become: yes
#  tasks:
#    - name: Install Docker-compose
#      get_url:
#        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
#        dest: /usr/local/bin/docker-compose
#        mode: +x

#- name: Start Docker
#  hosts: docker_server
#  become: yes
#  tasks:
#    - name: Ensure docker is running
#      systemd:
#        name: docker
#        state: started

- name: Create new linux user
#  hosts: docker_server
  hosts: all
  become: yes
  vars_files:
    - project-vars
  tasks:
    - name: Create new linux user
      user:
        name: shuvo
        groups: "{{user_groups}}" # no need reset connection for creating new user, reset connection need to change group for existing user

#- name: Test docker pull
#  hosts: docker_server
#  tasks:
#    - name: Pull redis
#      community.docker.docker_image:
#        name: redis
#        source: pull

- name: Start docker containers
#  hosts: docker_server
  hosts: all
#  vars_prompt:
#    - name: docker_password
#      prompt: Enter password for docker registry
  become: yes
  become_user: shuvo
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: /f/Shanto_PC/BdCalling/online-shop-microservices/ansible-ec2/docker-compose.yaml
        dest: /home/shuvo/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: shuvo83qn
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/shuvo
        state: present # docker-compose up, absent: docker-compose down
