---
- name: Install python3, docker and docker-compose on EC2
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker is installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: 
         - docker
         - docker-compose

#- name: Install Docker on EC2
#  hosts: docker_server
#  become: yes
#  tasks:
#    - name: Install Docker
#      vars:
#        ansible_python_interpreter: /usr/bin/python
#      yum:
#        name: docker
#        update_cache: yes
#        state: present

#- name: Install Docker-compose
#  hosts: docker_server
#  become: yes
#  tasks:
#    - name: Install Docker-compose
#      get_url:
#        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
#        dest: /usr/local/bin/docker-compose
#        mode: +x

#- name: Start Docker
#  hosts: docker_server
#  become: yes
#  tasks:
#    - name: Ensure docker is running
#      systemd:
#        name: docker
#        state: started

- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server-session
      meta: reset_connection

#- name: Test docker pull
#  hosts: docker_server
#  tasks:
#    - name: Pull redis
#      community.docker.docker_image:
#        name: redis
#        source: pull

- name: Start docker containers
  hosts: docker_server
#  vars_prompt:
#    - name: docker_password
#      prompt: Enter password for docker registry
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: /f/Shanto_PC/BdCalling/online-shop-microservices/ansible-ec2/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: shuvo83qn
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        state: present # docker-compose up, absent: docker-compose down
