---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
#        kubeconfig: ~/f/Shanto_PC/BdCalling/online-shop-microservices/ansible-eks/terraform-eks-project/kubeconfig_myapp-eks-cluster/kubeconfig_myapp-eks-cluster
    - name: Deploy nginx app
      community.kubernetes.k8s:
        src: ~/f/Shanto_PC/BdCalling/online-shop-microservices/ansible-eks/k8s-files/nginx-config.yaml
        state: present # absent for delete
        kubeconfig: ~/f/Shanto_PC/BdCalling/online-shop-microservices/ansible-eks/terraform-eks-project/kubeconfig_myapp-eks-cluster/kubeconfig_myapp-eks-cluster
        namespace: my-app


