apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: busybox-container
      image: busybox
      volumeMounts:
      - mountPath: "/etc/config"
        name: config-dir
  volumes:
    - name: config-dir
      configMap:
        name: bb-configmap