---
- name: Install python3, docker and docker-compose on EC2
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker is installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: 
         - docker
         - docker-compose

