apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: Group 
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io 
  namespace: kube-system //ServiceAccount
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io