apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "pods", "services", "deployments"]
  verbs: ["get", "create", "list", "delete", "update"]
  resourceNames: ["myapp"]
