apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-developer-binding
subjects:
- kind: User //Group //ServiceAccount
  name: jane //"devops-admins" //default
  apiGroup: rbac.authorization.k8s.io 
  namespace: kube-system //ServiceAccount
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io